### ISSUE TITLE
Switch to using babbage

### ISSUE THREAD

**Issue by pudo** [openspending/cubepress#5]
It's a more mature, well-tested aggregator, will help to cut out the bulk of the code base.

**Comment by rgrp** [comment]
@pudo would this be a wholesale merge across?

Also would we be happy to refactor any parts of babbage as needed to conform to the spec we determine and support the relevant API - see #4 description which now has more detail on what is planned based on all the convos last week.

**Comment by pudo** [comment]
@rgrp see the PR: basically the idea is to use libraries for all those pieces where they exist. In this sense, ``babbage`` is just a pre-packaged way to generate aggregated somewhat systematically. 

As for refactoring babbage, very happy to do so. It is also the backend to SpenDB and so I'll need to pull that along and migrate both the existing datasets and the model configuration UI. It's also the result of a few months of development and the learning from OpenSpending and Cubes.

So I would ask that any refactoring serves the purpose of making better aggregations and not just implementing a spec. Otherwise, adaptors might be better.

**Comment by danfowler** [comment]
Closing this issue as this has been merged, and we are moving forward with using babbage for generating aggregates directly.
